/**
 * Cheat Sheet PDF (BUILD_PROMPT feature 13): one-page export — top 8
 * questions, the user's best answers (condensed), company facts, 3
 * questions-to-ask — via @react-pdf/renderer, small app watermark footer
 * (shareable = growth, PLAYBOOK 3.4).
 */
import "server-only";
import React from "react";
import { Document, Page, Text, View, StyleSheet, renderToBuffer, Font } from "@react-pdf/renderer";
import type { PrepQuestion, SavedAnswer } from "@/lib/types";

const styles = StyleSheet.create({
  page: { padding: 32, fontSize: 9.5, fontFamily: "Helvetica", color: "#1A1A1A" },
  header: { marginBottom: 12, borderBottom: "1.5pt solid #0F2A43", paddingBottom: 8 },
  title: { fontSize: 17, fontFamily: "Helvetica-Bold", color: "#0F2A43" },
  subtitle: { fontSize: 9, color: "#5B6472", marginTop: 2 },
  section: { marginTop: 10 },
  sectionTitle: { fontSize: 10, fontFamily: "Helvetica-Bold", color: "#B08D4A", marginBottom: 4, textTransform: "uppercase", letterSpacing: 0.5 },
  intel: { fontSize: 9, lineHeight: 1.4, color: "#333" },
  qBlock: { marginBottom: 7 },
  question: { fontFamily: "Helvetica-Bold", fontSize: 9.5, color: "#0F2A43" },
  outline: { fontSize: 8.5, color: "#333", marginTop: 1.5, lineHeight: 1.35 },
  askItem: { fontSize: 9, color: "#333", marginBottom: 2 },
  footer: { position: "absolute", bottom: 20, left: 32, right: 32, fontSize: 7, color: "#9AA3AE", textAlign: "center", borderTop: "0.5pt solid #E4E0D8", paddingTop: 6 },
});

const ASK_QUESTIONS = [
  "What does success look like in this role after the first 90 days?",
  "What's the biggest challenge someone in this seat will face this year?",
  "How does the team measure impact, and how often is it reviewed?",
];

function CheatSheetDoc({
  company,
  role,
  companyIntel,
  questions,
  bestAnswers,
}: {
  company: string;
  role: string;
  companyIntel: string;
  questions: PrepQuestion[];
  bestAnswers: SavedAnswer[];
}) {
  const top8 = questions.slice(0, 8);
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Interview Cheat Sheet — {company}</Text>
          <Text style={styles.subtitle}>{role} · Prepared with InterviewAce</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Company facts</Text>
          <Text style={styles.intel}>{companyIntel}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Top 8 questions</Text>
          {top8.map((q, i) => (
            <View key={i} style={styles.qBlock} wrap={false}>
              <Text style={styles.question}>
                {i + 1}. {q.question}
              </Text>
              <Text style={styles.outline}>{q.strong_answer_outline}</Text>
            </View>
          ))}
        </View>

        {bestAnswers.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Your best answers</Text>
            {bestAnswers.slice(0, 4).map((a, i) => (
              <View key={i} style={styles.qBlock} wrap={false}>
                <Text style={styles.question}>{a.question}</Text>
                <Text style={styles.outline}>{a.answer.slice(0, 320)}</Text>
              </View>
            ))}
          </View>
        )}

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Questions to ask them</Text>
          {ASK_QUESTIONS.map((q, i) => (
            <Text key={i} style={styles.askItem}>
              • {q}
            </Text>
          ))}
        </View>

        <Text style={styles.footer} fixed>
          Generated by InterviewAce — interviewace.app · Your interview is soon. Be ready.
        </Text>
      </Page>
    </Document>
  );
}

export async function renderCheatSheetPdf(args: {
  company: string;
  role: string;
  companyIntel: string;
  questions: PrepQuestion[];
  bestAnswers: SavedAnswer[];
}): Promise<Buffer> {
  return renderToBuffer(<CheatSheetDoc {...args} />);
}
